version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user_patri
      POSTGRES_PASSWORD: '1234'
    volumes:
      - ./csv_data:/var/lib/postgresql/d/data2
    ports:
      - 8080:8080


