version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: initexample
      POSTGRES_USER: initexample
      POSTGRES_HOST: postgres
      POSTGRES_DB: initexample
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432