version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - '5432:5432'

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
